<?php
/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the MIT license.
 */ 
?>

<h1>Your warnings</h1>

<table>
    <thead>
        <tr>
            <td>Time</td>
            <td>By</td>
            <td>Reason</td>
            <td>Weight</td>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->warnings as $warning) {
            echo '<tr>
                <td>' . $warning->getDate()->format('d-m-y H:i') . '</td>
                <td>' . $this->ZfcUserDisplayNameByUserId($warning->getUserBy()) . '</td>
                <td>' . $this->escapeHtml($warning->getReason()) . '</td>
                <td>' . $warning->getWeight() . '</td>
            </tr>';
        }
        ?>
    </tbody>
</table>
